# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forkify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forkify
	
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'PKHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'Ji'
  
  target 'ForkifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForkifyUITests' do
    # Pods for testing
  end

end
